- name: install and run nginx
  hosts: web
  become: yes # equal to -b(become root) in adhoc commands, getting root access
  tasks: 
  - name: install nginx
    ansible.builtin.dnf: # To work for all Distributions -> dnf  (.yum module-> Works only for RHEL)
      name: nginx
      state: latest #Installing latest version
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

#To RUN
#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 02-nginx.yaml

# state Choices: --> Choices: "reloaded" "restarted" "started" "stopped"
















