- name: PLAY-1
  hosts: localhost #Which we are running (SuperPutty)
  tasks: 
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:  # debug to Print the message on console
      msg: "Hello I am from PLAY-1 and TASK-1"

  - name: PLAY-2 and TASK-1
    ansible.builtin.debug:
      msg: "Hello I am from PLAY-2 and TASK-1"

















