- name: variables
  hosts: localhost
  vars: #Variable Decleration in PLAY LEVEL
    Course: Terraform
    Trainer: Siva
    Duration: "15hrs"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}}...."
