- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}}...."

  - name: print Task Level information
    vars:
      timing: "7:15 AM to 9:00 AM"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}} Total duration around {{Duration}} and Class Timing's are {{timing}}"

#No need to mention INVENTORY (Ansible will automatically will search)
#Search for All possible Locations...like: -> PLAYLEVEL -> TASK LEVEL -> FILES -> PROMPT -> Finally in Inventory file








