# Below checking when a variable is declared in all locations then from which location does Ansible will consider
- name: variable preference
  hosts: localhost
  # vars: 
  #   X: "Play Level Variable...."
  vars_files:
  - vars.yaml
  # vars_prompt:
  # - name: X
  #   prompt: Please Enter X
  #   private: false
  tasks: 
  - name: checking preference
    # vars:
    #   X: "VAR/TASK Level (Local Level) variable...."
    ansible.builtin.debug:
      msg: "Hello, Iam from {{X}}"


# 1st Preference is From ARGUMENTS
# 2nd Task Level
# 3rd Variable Files
# 4th Prompt
# 5th PLAY Level
# 6th Inventory

