- name: data types
  hosts: locahost
  vars:
    Course: DevOps with AWS #It is a String
    Tools:  # List
    - Linux
    - Shell
    - Ansible
    Experience: #MAP/Dictionary  (Key)
      DevOps: 3  #Number  (Value)
      AWS: 2
      Docker: 1
    RealProject: true #Boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"







