- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense #Here user not available then create user
    register: USER  #Out ut of expense store in USER Var In Shell taking output from input ( X=$(NAME))
    ignore_errors: true #We know error will come here saying just ignore

  - name: print user information
    ansible.builtin.debug:
      msg: "User info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense #Should run when rc: 0 
    when: USER.rc !=0 #Run's Command #User dosen't exist then add user
#No If else in Ansible only when

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"

      # 'rc': 1,  -> Exit status (0 successs,  Any Failure similar In Shell)