- name: default value
  hosts: localhost
  tasks: 
  - name: print default value
    ansible.builtin.debug:
      msg: "Hai {{z | default ('there')}}"  # | default (' ') --> ? When no value is passed then default value will be taken


- name: upper case
  hosts: localhost
  vars: 
    text: mani kanta
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{text | upper}}"


- name: upper case
  hosts: localhost
  vars:
    texts: MAni KanTA
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{texts | lower}}"



- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [2,4,1,4,6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"


- name: minimum and maximum
  hosts: localhost
  vars:
    ages: [21,34,23,76,43,67]
  tasks:
  - name: min and max
    ansible.builtin.debug:
      msg: "Minimum age is: {{ages | min}}, Maximum age is: {{ages | max}}"



- name: convert dictonary into items/list
  hosts: localhost
  my_dict:
    FirstName: Manikanta
    LastName: Konuganti
    Age: "21"
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before Convert: {{my_dict }}"

  - name: after convert
    ansible.builtin.debug:
      msg: "After Convert: {{my_dict | dict2items}}"


- name: convert items to dictonary
  hosts: localhost
  my_list:
  - {'key' : 'FirstName' , 'value': 'Jagan'}
  - {'key' : 'LastName' , 'value' : 'Konu'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{my_list}}"

  - name: After convert
    ansible.builtin.debug:
      msg: "After convert: {{my_list | items2dict}}"










