- name: default value
  hosts: localhost
  tasks: 
  - name: print default value
    ansible.builtin.debug:
      msg: "Hai {{z | default ('there')}}"  # | default (' ') --> ? When no value is passed then default value will be taken


- name: upper case
  hosts: localhost
  vars: 
    text: mani kanta
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{text | upper}}"


- name: upper case
  hosts: localhost
  vars:
    texts: MAni KanTA
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{texts | lower}}"



- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [2,4,1,4,6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"











