- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'I am from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.shell: "echo 'I am from shell module' > /tmp/shell.txt "

# This is faster bcz? --> It dosen't need Environment to run
# command module --> it will just run the commands, but can't use shell environment like > , pipe | or variables.
# if you want to run shell script inside ansible or complex commands with redirections then we can use shell module
#What ever work's in Command module will also work in Shell Module (But not reverse)

# This is bit slower ? --> It needs Environment to run
# shell module --> it will use shell environment, means we can use redirections >, pipes | and other shell variables
# if a simple plain command with out variables, redirections, pipes, etc. we can use command module..


