- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'I am from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.shell: "echo 'I am from shell module' > /tmp/shell.txt "